"""
Hello_Word
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

from airflow import DAG
from airflow.utils.dates import days_ago
import random

@aql.dataframe(task_id="Hello_Word")
def Hello_Word_func():
    
    
    with DAG(dag_id='example_dag_basic', start_date=days_ago(2), schedule=None, catchup=False) as dag:
    
        @dag.task
        def make_list():
            return [random.randint(1, 100) for i in range(random.randint(2, 5))]
    
        @dag.task
        def consumer(value):
            return value + 10
    
        consumer.expand(value=make_list())

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-06-06", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def Hello_Word():
    Hello_Word = Hello_Word_func()

dag_obj = Hello_Word()
