"""
WWss
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator

@aql.dataframe(task_id="task")
def task_func():
    def print_hello():
        return 'Hello world from first Airflow DAG!'
    
    dag = DAG('hello_world', description='Hello World DAG',
              schedule_interval='0 12 * * *',
              start_date=datetime(2017, 3, 20), catchup=False)
    
    hello_operator = PythonOperator(task_id='hello_task', python_callable=print_hello, dag=dag)
    
    hello_operator

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-06-06", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def WWss():
    task = task_func()

dag_obj = WWss()
