"""
WWss
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

import pandas as pd

@aql.dataframe(task_id="task")
def task_func():
    print('hello')

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-06-06", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def WWss():
    task = task_func()

dag_obj = WWss()
